apiVersion: apps/v1
kind: Deployment
metadata:
  name: <what points here?>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <what points here?>
  template:
    metadata:
      labels:
        app: <what points here?>
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379