name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      STUDENT: ${{ vars.CSCCUID }}
      ACR_HOST: ${{ vars.ACR_HOST }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build . -f Dockerfile_with_redis -t $ACR_HOST/week11-example/${{ env.STUDENT }}:v2
          docker push $ACR_HOST/week11-example/${{ env.STUDENT }}:v2